# Generated by Django 5.0.6 on 2026-05-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0006_proposal_length"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="generationevent",
            new_name="proposals_g_org_id_083ee0_idx",
            old_name="proposals_g_org_id_created_idx",
        ),
    ]
