# Generated by Django 5.0.6 on 2026-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_rename_proposals_g_org_id_created_idx_proposals_g_org_id_083ee0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=30),
        ),
    ]
