# Generated by Django 5.0.6 on 2026-06-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_add_ai_model_to_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='ai_model',
        ),
    ]
