# Generated by Django 5.2.15 on 2026-06-10 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_invitation'),
        ('proposals', '0009_remove_proposal_ai_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('data', 'Data'), ('design', 'Design'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], default='other', max_length=20)),
                ('accent', models.CharField(default='violet', max_length=20)),
                ('sections', models.JSONField(default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['org', 'is_active'], name='proposals_t_org_id_7ba8e5_idx')],
            },
        ),
    ]
