import { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate, useLocation } from "react-router-dom";
import {
    Paperclip,
    Send,
    X,
    FileText,
    ChevronDown,
    Sparkles,
    ArrowRight,
    Plus,
    Wand2,
    Layers,
    LayoutTemplate,
} from "lucide-react";
import { toast } from "react-hot-toast";
import { suggestionChips, coreFeatures, tones, sampleProposalSections } from "../lib/mock-data";
import useAuthStore from "../store/auth";
import api from "../api/client";

const LENGTH_OPTIONS = [
    { value: "concise", label: "Concise", hint: "~1 paragraph per section" },
    { value: "standard", label: "Standard", hint: "~2 paragraphs per section" },
    { value: "detailed", label: "Detailed", hint: "2–3 deep paragraphs" },
    { value: "comprehensive", label: "Comprehensive", hint: "3–4 paragraphs, max depth" },
];

const STAGE_LABELS = {
    queued: "Queued…",
    analyzing: "Analyzing RFP intent",
    retrieving: "Pulling from knowledge base",
    drafting: "Drafting proposal sections",
    polishing: "Polishing tone & language",
    done: "Done",
    failed: "Failed",
};

function buildTicker(stage, meta = {}) {
    const out = [];
    if (stage === "analyzing") {
        out.push("Reading buyer requirements", "Identifying compliance signals", "Inferring tone preference");
    } else if (stage === "retrieving") {
        if (meta.client) out.push(`Client: ${meta.client}`);
        if (meta.industry) out.push(`Industry: ${meta.industry}`);
        out.push("Embedding RFP query", "Searching vector store", "Reranking top matches");
    } else if (stage === "drafting") {
        if (meta.chunks) {
            const docCount = Array.isArray(meta.docs) ? meta.docs.length : 0;
            out.push(`Matched ${meta.chunks} chunks across ${docCount || "your"} docs`);
        }
        if (meta.top_source) out.push(`Top match: ${meta.top_source}`);
        if (meta.rerank_used) out.push("Cohere rerank applied");
        out.push("Drafting all 10 sections", "Composing executive narrative");
    } else if (stage === "polishing") {
        if (meta.provider) out.push(`Generated by ${meta.provider}`);
        out.push("Finalizing 10 sections", "Almost there…");
    } else {
        out.push("Warming up…");
    }
    return out;
}

// Build final prompt: template title + user requirements only.
// Section list is sent separately on the RFP payload (`sections` field) so the
// backend builds the LLM JSON schema dynamically.
function buildFinalPrompt(template, requirements) {
    const reqText = requirements.trim() || "Please use professional judgment to draft a comprehensive proposal.";
    return `I need a proposal for a ${template.title} project.\n\nClient requirements and context:\n${reqText}\n\nPlease draft a complete, professional, and detailed proposal. Structure it clearly with our branding and preferred tone.`;
}

export function Generator() {
    const location = useLocation();
    const incomingTemplate = location.state?.template ?? null;

    const [phase, setPhase] = useState("idle");
    const [input, setInput] = useState("");
    const [files, setFiles] = useState([]);
    const [tone, setTone] = useState("Persuasive");
    const [toneOpen, setToneOpen] = useState(false);
    const [lengthIdx, setLengthIdx] = useState(1); // 0=concise, 1=standard, 2=detailed, 3=comprehensive
    const [stage, setStage] = useState("queued");
    const [stageMeta, setStageMeta] = useState({});
    const [elapsed, setElapsed] = useState(0);
    const [tickerIdx, setTickerIdx] = useState(0);
    const [isDragging, setIsDragging] = useState(false);
    const [proposalId, setProposalId] = useState(null);
    const [activeTemplate, setActiveTemplate] = useState(null);
    const [activeSections, setActiveSections] = useState([]);
    const [addingSection, setAddingSection] = useState(false);
    const [newSectionName, setNewSectionName] = useState("");
    const fileRef = useRef(null);
    const pollRef = useRef(null);
    const addSectionRef = useRef(null);
    const navigate = useNavigate();
    const user = useAuthStore((s) => s.user);
    const displayName = user?.email?.split("@")[0] ?? "there";
    const initials = displayName.slice(0, 2).toUpperCase();

    // Apply incoming template on mount
    useEffect(() => {
        if (incomingTemplate) {
            setActiveTemplate(incomingTemplate);
            setActiveSections(incomingTemplate.sections);
            setInput(""); // textarea is for client requirements only
            // Clear router state so refreshing doesn't re-apply
            window.history.replaceState({}, "");
        }
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    function dismissTemplate() {
        setActiveTemplate(null);
        setActiveSections([]);
        setAddingSection(false);
        setNewSectionName("");
        setInput("");
    }

    function attach(list) {
        if (!list) return;
        const next = Array.from(list).map((f, i) => ({
            id: `${Date.now()}-${i}`,
            name: f.name,
            size: `${(f.size / 1024).toFixed(0)} KB`,
            file: f,
        }));
        setFiles((p) => [...p, ...next]);
    }

    function removeFile(id) {
        setFiles((p) => p.filter((f) => f.id !== id));
    }

    const MIN_CHARS = 200;
    const MIN_WORDS = 30;
    const ALLOWED_EXTS = ["pdf", "docx", "txt"];
    const MAX_FILE_BYTES = 10 * 1024 * 1024;

    async function generate() {
        const trimmed = input.trim();
        const hasFile = files.length > 0 && !!files[0]?.file;

        // Section guard — only when template is active
        if (activeTemplate && activeSections.length === 0) {
            toast.error("Add at least one section to include in the proposal.");
            return;
        }

        if (!trimmed && !hasFile) {
            toast.error(
                activeTemplate
                    ? "Describe your client's requirements or upload a document."
                    : "Type an RFP brief or attach a file."
            );
            return;
        }

        if (hasFile) {
            const f = files[0].file;
            const ext = f.name.split(".").pop()?.toLowerCase() || "";
            if (!ALLOWED_EXTS.includes(ext)) {
                toast.error(`Unsupported file type .${ext}. Allowed: pdf, docx, txt.`);
                return;
            }
            if (f.size === 0) {
                toast.error("Uploaded file is empty.");
                return;
            }
            if (f.size > MAX_FILE_BYTES) {
                toast.error("File exceeds 10 MB limit.");
                return;
            }
        } else if (!activeTemplate) {
            // Only enforce char/word minimums for free-form text (no template selected)
            if (trimmed.length < MIN_CHARS) {
                toast.error(`RFP too short. Need at least ${MIN_CHARS} characters describing scope and requirements.`);
                return;
            }
            if (trimmed.split(/\s+/).length < MIN_WORDS) {
                toast.error(`RFP too short. Need at least ${MIN_WORDS} words describing scope and requirements.`);
                return;
            }
        }

        // Build the final prompt — merge title + requirements when template is active.
        // Sections themselves are sent as a separate structured field below.
        const finalPrompt = activeTemplate
            ? buildFinalPrompt(activeTemplate, trimmed)
            : trimmed;

        setPhase("thinking");
        setStage("queued");
        setStageMeta({});
        setElapsed(0);
        setTickerIdx(0);
        setProposalId(null);

        try {
            // Only send an explicit title when a template is active — its name is a proper label.
            // For free-form input the backend will extract a smart title from the RFP text.
            const title = activeTemplate?.title ?? "";
            const customSections = activeTemplate ? activeSections : [];
            let rfpPayload = { raw_text: finalPrompt };
            if (title) rfpPayload.title = title;
            if (customSections.length) rfpPayload.sections = customSections;
            let rfpConfig;
            if (files[0]?.file) {
                rfpPayload = new FormData();
                if (title) rfpPayload.append("title", title);
                rfpPayload.append("raw_text", finalPrompt);
                rfpPayload.append("file", files[0].file);
                // FormData: append each section as repeated `sections` entries so DRF ListField parses them.
                customSections.forEach((s) => rfpPayload.append("sections", s));
                rfpConfig = { headers: { "Content-Type": "multipart/form-data" } };
            }
            const { data: rfp } = await api.post("/rfps/", rfpPayload, rfpConfig);
            toast.success("RFP saved — generating proposal…");
            const length = LENGTH_OPTIONS[lengthIdx]?.value ?? "standard";
            const { data: proposal } = await api.post(`/rfps/${rfp.id}/generate/`, {
                tone: tone.toLowerCase(),
                length,
            });
            setProposalId(proposal.id);

            pollRef.current = setInterval(async () => {
                try {
                    const { data } = await api.get(`/proposals/${proposal.id}/`);
                    if (data.status_stage) setStage(data.status_stage);
                    if (data.stage_meta) setStageMeta(data.stage_meta);
                    if (data.status === "draft") {
                        clearInterval(pollRef.current);
                        setStage("done");
                        setTimeout(() => setPhase("result"), 350);
                    } else if (data.status === "failed") {
                        clearInterval(pollRef.current);
                        toast.error("Proposal generation failed. Please try again.");
                        reset();
                    }
                } catch {
                    clearInterval(pollRef.current);
                    toast.error("Lost connection while generating.");
                    reset();
                }
            }, 2000);
        } catch (err) {
            toast.error(err.response?.data?.detail || "Failed to create RFP.");
            reset();
        }
    }

    function reset() {
        clearInterval(pollRef.current);
        setPhase("idle");
        setInput("");
        setFiles([]);
        setStage("queued");
        setStageMeta({});
        setElapsed(0);
        setTickerIdx(0);
        setProposalId(null);
        setActiveTemplate(null);
        setActiveSections([]);
        setAddingSection(false);
        setNewSectionName("");
    }

    // Elapsed timer while generating
    useEffect(() => {
        if (phase !== "thinking") return;
        const t = setInterval(() => setElapsed((e) => e + 1), 1000);
        return () => clearInterval(t);
    }, [phase]);

    // Reset ticker index whenever stage changes
    useEffect(() => {
        setTickerIdx(0);
    }, [stage]);

    // Rotate ticker every 1.8s through messages built from stageMeta
    const tickerMessages = buildTicker(stage, stageMeta);
    useEffect(() => {
        if (phase !== "thinking" || tickerMessages.length <= 1) return;
        const t = setInterval(() => {
            setTickerIdx((i) => (i + 1) % tickerMessages.length);
        }, 1800);
        return () => clearInterval(t);
    }, [phase, stage, tickerMessages.length]);

    useEffect(() => () => clearInterval(pollRef.current), []);

    function openInEditor() {
        if (proposalId) navigate(`/proposals/${proposalId}`);
    }

    return (
        <div
            className="relative flex min-h-dvh flex-col"
            onDragOver={(e) => {
                e.preventDefault();
                setIsDragging(true);
            }}
            onDragLeave={() => setIsDragging(false)}
            onDrop={(e) => {
                e.preventDefault();
                setIsDragging(false);
                attach(e.dataTransfer.files);
            }}
        >
            {/* Top bar */}
            <header className="flex items-center justify-between px-6 py-3">
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <span className="inline-flex h-2 w-2 rounded-full bg-cyan shadow-[0_0_10px_var(--cyan)]" />
                    <span className="font-mono uppercase tracking-widest">Session · live</span>
                </div>
                <div className="flex items-center gap-3">
                    {phase !== "idle" && (
                        <button
                            onClick={reset}
                            className="flex items-center gap-1.5 rounded-full border border-hairline bg-surface/60 px-3 py-1.5 text-xs text-foreground/85 backdrop-blur hover:border-violet/40"
                        >
                            <Plus className="h-3.5 w-3.5" /> New chat
                        </button>
                    )}
                    <span className="hidden text-sm text-muted-foreground sm:inline">{displayName}</span>
                    <div className="relative h-9 w-9 overflow-hidden rounded-full ring-1 ring-violet/50">
                        <span className="absolute inset-0 bg-gradient-to-br from-violet to-magenta" />
                        <span className="relative z-10 flex h-full w-full items-center justify-center text-xs font-semibold text-white">
                            {initials}
                        </span>
                    </div>
                </div>
            </header>

            {/* Scrollable content area — leaves room for fixed input */}
            <div className="flex flex-1 flex-col items-center px-6 pb-[220px]">
                <AnimatePresence mode="wait">
                    {phase === "idle" && (
                        <motion.div
                            key="hero"
                            initial={{ opacity: 0, y: 12 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -12 }}
                            transition={{ duration: 0.5 }}
                            className="mt-4 w-full max-w-3xl text-center"
                        >
                            {/* ── Template Banner ── */}
                            <AnimatePresence>
                                {activeTemplate && (
                                    <motion.div
                                        key="template-banner"
                                        initial={{ opacity: 0, y: -12, scale: 0.97 }}
                                        animate={{ opacity: 1, y: 0, scale: 1 }}
                                        exit={{ opacity: 0, y: -8, scale: 0.97 }}
                                        transition={{ type: "spring", stiffness: 300, damping: 28 }}
                                        className="relative mb-8 overflow-hidden rounded-2xl border border-violet/40 bg-surface/70 p-5 text-left backdrop-blur-md shadow-[var(--shadow-glow-violet)]"
                                    >
                                        {/* shimmer top edge */}
                                        <span className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-violet to-transparent opacity-70" />
                                        {/* glow corner */}
                                        <span className="pointer-events-none absolute -top-10 -left-10 h-28 w-28 rounded-full bg-violet/30 blur-2xl" />

                                        <div className="relative flex items-start gap-4">
                                            <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-violet/20 ring-1 ring-violet/50">
                                                <LayoutTemplate className="h-5 w-5 text-violet" />
                                            </span>
                                            <div className="min-w-0 flex-1">
                                                <p className="font-mono text-[10px] uppercase tracking-widest text-violet">Template selected</p>
                                                <h3 className="mt-0.5 font-display text-base font-semibold text-foreground">{activeTemplate.title}</h3>
                                                <div className="mt-3 flex items-center gap-1.5 text-[11px] text-muted-foreground">
                                                    <Layers className="h-3.5 w-3.5 text-violet" />
                                                    <span>{activeSections.length} sections loaded</span>
                                                    <span className="text-violet/50">·</span>
                                                    <span className="text-violet/80">customise in the input below</span>
                                                </div>
                                            </div>
                                            <button
                                                onClick={dismissTemplate}
                                                aria-label="Dismiss template"
                                                className="shrink-0 rounded-full p-1.5 text-muted-foreground hover:bg-surface-2 hover:text-foreground transition"
                                            >
                                                <X className="h-4 w-4" />
                                            </button>
                                        </div>

                                        <div className="relative mt-4 flex items-center gap-2 border-t border-hairline pt-3">
                                            <span className="h-1.5 w-1.5 rounded-full bg-cyan shadow-[0_0_8px_var(--cyan)]" />
                                            <p className="text-xs text-muted-foreground">
                                                Sections are pre-loaded below — add, remove, or keep as-is. Then describe your client&apos;s requirements.
                                            </p>
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>

                            {/* ── Default hero (only when no template) ── */}
                            {!activeTemplate && (
                                <>
                                    <p className="font-display text-2xl font-medium tracking-tight text-foreground sm:text-3xl">
                                        Welcome back, <span className="text-magenta-gradient">{displayName}</span>
                                    </p>
                                    <h1 className="mt-3 font-display text-2xl font-semibold tracking-tight text-balance sm:text-4xl">
                                        What would you like to <span className="text-gradient">propose</span> today?
                                    </h1>
                                    <p className="mt-2 text-sm text-muted-foreground">
                                        Describe your RFP or attach documents. Draftly drafts a polished, on-brand proposal in seconds.
                                    </p>

                                    {/* Suggestion chips */}
                                    <motion.div
                                        initial={{ opacity: 0, y: 8 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ delay: 0.2 }}
                                        className="mx-auto mt-5 flex flex-wrap justify-center gap-2"
                                    >
                                        {suggestionChips.map((s, i) => (
                                            <motion.button
                                                key={s}
                                                whileHover={{ y: -2 }}
                                                onClick={() => setInput(s)}
                                                initial={{ opacity: 0, y: 8 }}
                                                animate={{ opacity: 1, y: 0 }}
                                                transition={{ delay: 0.25 + i * 0.05 }}
                                                className="glass group flex items-center gap-2 rounded-full px-4 py-2 text-xs text-foreground/85 transition hover:text-foreground"
                                            >
                                                <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-gradient-to-br from-violet/40 to-cyan/40 ring-1 ring-violet/40">
                                                    <Sparkles className="h-3 w-3 text-cyan" />
                                                </span>
                                                {s}
                                            </motion.button>
                                        ))}
                                    </motion.div>

                                    {/* Core Features */}
                                    <div className="mx-auto mt-6 w-full max-w-4xl text-left">
                                        <p className="mb-3 font-display text-sm font-medium text-foreground/90">Core Features</p>
                                        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
                                            {coreFeatures.map((f, i) => {
                                                const accents = [
                                                    { ring: "ring-cyan/40", text: "text-cyan", color: "var(--cyan)" },
                                                    { ring: "ring-violet/40", text: "text-violet", color: "var(--violet)" },
                                                    { ring: "ring-magenta/40", text: "text-magenta", color: "var(--magenta)" },
                                                ][i % 3];
                                                return (
                                                    <FeatureCard
                                                        key={f.id}
                                                        feature={f}
                                                        accents={accents}
                                                        index={i}
                                                    />
                                                );
                                            })}
                                        </div>
                                    </div>
                                </>
                            )}
                        </motion.div>
                    )}

                    {phase === "thinking" && (
                        <motion.div
                            key="thinking"
                            initial={{ opacity: 0, scale: 0.96 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0 }}
                            className="mt-6 w-full max-w-3xl"
                        >
                            <ThinkingStage
                                files={files}
                                stage={stage}
                                stageLabel={STAGE_LABELS[stage] ?? "Working…"}
                                ticker={tickerMessages[tickerIdx] ?? ""}
                                elapsed={elapsed}
                            />
                        </motion.div>
                    )}

                    {phase === "result" && (
                        <motion.div
                            key="result"
                            initial={{ opacity: 0, y: 16 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5 }}
                            className="mt-8 w-full max-w-3xl"
                        >
                            <ResultCard
                                onOpen={openInEditor}
                                title={activeTemplate?.title || "Your proposal is ready"}
                                tone={tone}
                            />
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            {/* FIXED bottom input */}
            <div className="pointer-events-none fixed bottom-0 left-[72px] right-0 z-30 px-6 pb-4">
                <div className="pointer-events-none absolute inset-x-0 bottom-0 -z-10 h-48 bg-gradient-to-t from-background via-background/85 to-transparent" />
                <div className="pointer-events-auto mx-auto w-full max-w-4xl">
                    <div className={`input-ring relative shadow-panel transition ${isDragging ? "scale-[1.01]" : ""}`}>
                        <div className="relative rounded-[17px] p-4" style={{ background: "var(--input-bg)" }}>
                            {/* file chips */}
                            {files.length > 0 && (
                                <div className="mb-3 flex flex-wrap gap-2">
                                    <AnimatePresence>
                                        {files.map((f) => (
                                            <motion.div
                                                key={f.id}
                                                layout
                                                initial={{ opacity: 0, scale: 0.85, y: 4 }}
                                                animate={{ opacity: 1, scale: 1, y: 0 }}
                                                exit={{ opacity: 0, scale: 0.85, y: -4 }}
                                                className="group flex items-center gap-2 rounded-full border border-violet/40 bg-violet/10 px-3 py-1.5 text-xs"
                                            >
                                                <FileText className="h-3.5 w-3.5 text-violet" />
                                                <span className="max-w-[180px] truncate text-foreground">{f.name}</span>
                                                <span className="text-muted-foreground">{f.size}</span>
                                                <button
                                                    aria-label={`Remove ${f.name}`}
                                                    onClick={() => removeFile(f.id)}
                                                    className="ml-1 text-muted-foreground hover:text-magenta"
                                                >
                                                    <X className="h-3.5 w-3.5" />
                                                </button>
                                            </motion.div>
                                        ))}
                                    </AnimatePresence>
                                </div>
                            )}

                            {/* Section chips — ONLY shown when a template is active */}
                            <AnimatePresence>
                                {activeTemplate && (
                                    <motion.div
                                        key="section-chips"
                                        initial={{ opacity: 0, height: 0 }}
                                        animate={{ opacity: 1, height: "auto" }}
                                        exit={{ opacity: 0, height: 0 }}
                                        className="mb-3 overflow-hidden"
                                    >
                                        <div className="mb-2 flex items-center gap-1.5 text-[10px] text-muted-foreground">
                                            <Layers className="h-3 w-3 text-violet" />
                                            <span className="font-mono uppercase tracking-widest">Sections to include</span>
                                        </div>
                                        <div className="flex flex-wrap gap-1.5">
                                            <AnimatePresence mode="popLayout">
                                                {activeSections.map((s) => (
                                                    <motion.span
                                                        key={s}
                                                        layout
                                                        initial={{ opacity: 0, scale: 0.8 }}
                                                        animate={{ opacity: 1, scale: 1 }}
                                                        exit={{ opacity: 0, scale: 0.8 }}
                                                        className="flex items-center gap-1.5 rounded-full border border-violet/40 bg-violet/10 px-2.5 py-1 text-[11px] text-violet"
                                                    >
                                                        {s}
                                                        <button
                                                            onClick={() => setActiveSections((p) => p.filter((x) => x !== s))}
                                                            className="text-violet/50 transition hover:text-violet"
                                                            aria-label={`Remove ${s} section`}
                                                        >
                                                            <X className="h-3 w-3" />
                                                        </button>
                                                    </motion.span>
                                                ))}
                                            </AnimatePresence>

                                            {addingSection ? (
                                                <motion.div
                                                    initial={{ opacity: 0, scale: 0.9 }}
                                                    animate={{ opacity: 1, scale: 1 }}
                                                >
                                                    <input
                                                        ref={addSectionRef}
                                                        autoFocus
                                                        value={newSectionName}
                                                        onChange={(e) => setNewSectionName(e.target.value)}
                                                        onKeyDown={(e) => {
                                                            if (e.key === "Enter" && newSectionName.trim()) {
                                                                setActiveSections((p) => [...p, newSectionName.trim()]);
                                                                setNewSectionName("");
                                                                setAddingSection(false);
                                                            }
                                                            if (e.key === "Escape") {
                                                                setAddingSection(false);
                                                                setNewSectionName("");
                                                            }
                                                        }}
                                                        onBlur={() => {
                                                            if (newSectionName.trim()) {
                                                                setActiveSections((p) => [...p, newSectionName.trim()]);
                                                            }
                                                            setNewSectionName("");
                                                            setAddingSection(false);
                                                        }}
                                                        placeholder="Section name…"
                                                        className="w-32 rounded-full border border-violet/50 bg-violet/10 px-2.5 py-1 text-[11px] text-violet placeholder:text-violet/40 focus:outline-none"
                                                    />
                                                </motion.div>
                                            ) : (
                                                <motion.button
                                                    whileHover={{ scale: 1.04 }}
                                                    onClick={() => setAddingSection(true)}
                                                    className="flex items-center gap-1 rounded-full border border-dashed border-violet/30 px-2.5 py-1 text-[11px] text-violet/60 transition hover:border-violet/60 hover:text-violet"
                                                >
                                                    <Plus className="h-3 w-3" /> Add section
                                                </motion.button>
                                            )}
                                        </div>
                                        {activeSections.length === 0 && (
                                            <p className="mt-2 text-[10px] text-amber-400/80">⚠ Add at least one section to generate the proposal.</p>
                                        )}
                                        <div className="mt-3 border-t border-hairline" />
                                    </motion.div>
                                )}
                            </AnimatePresence>

                            <textarea
                                value={input}
                                onChange={(e) => setInput(e.target.value)}
                                rows={activeTemplate ? 3 : 2}
                                placeholder={
                                    activeTemplate
                                        ? "Describe your client's specific requirements, goals, or constraints…"
                                        : "Describe the proposal you need… or drop a PDF/DOCX RFP here."
                                }
                                className="block w-full resize-none bg-transparent text-sm leading-relaxed text-foreground placeholder:text-muted-foreground focus:outline-none sm:text-base"
                                onKeyDown={(e) => {
                                    if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) generate();
                                }}
                                disabled={phase === "thinking"}
                            />

                            <div className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t border-hairline pt-3">
                                <div className="flex items-center gap-2">
                                    <div className="relative">
                                        <button
                                            onClick={() => setToneOpen((v) => !v)}
                                            className="flex items-center gap-2 rounded-full border border-hairline bg-surface-2/60 px-3 py-1.5 text-xs text-foreground hover:border-violet/40"
                                        >
                                            <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                                                Tone
                                            </span>
                                            <span className="font-medium">{tone}</span>
                                            <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
                                        </button>
                                        <AnimatePresence>
                                            {toneOpen && (
                                                <motion.ul
                                                    initial={{ opacity: 0, y: 6 }}
                                                    animate={{ opacity: 1, y: 0 }}
                                                    exit={{ opacity: 0, y: 6 }}
                                                    className="glass-strong absolute bottom-full left-0 z-20 mb-2 w-44 overflow-hidden rounded-xl p-1 text-sm shadow-panel"
                                                >
                                                    {tones.map((t) => (
                                                        <li key={t}>
                                                            <button
                                                                onClick={() => {
                                                                    setTone(t);
                                                                    setToneOpen(false);
                                                                }}
                                                                className={`flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-xs transition hover:bg-violet/15 ${t === tone ? "text-cyan" : "text-foreground/85"
                                                                    }`}
                                                            >
                                                                {t}
                                                                {t === tone && (
                                                                    <span className="h-1.5 w-1.5 rounded-full bg-cyan shadow-[0_0_8px_var(--cyan)]" />
                                                                )}
                                                            </button>
                                                        </li>
                                                    ))}
                                                </motion.ul>
                                            )}
                                        </AnimatePresence>
                                    </div>

                                    {/* Length slider */}
                                    <LengthSlider value={lengthIdx} onChange={setLengthIdx} />

                                    {/* Confidence pill — shows section count + tone when template is active */}
                                    <AnimatePresence mode="wait">
                                        {activeTemplate ? (
                                            <motion.span
                                                key="confidence-pill"
                                                initial={{ opacity: 0, scale: 0.85 }}
                                                animate={{ opacity: 1, scale: 1 }}
                                                exit={{ opacity: 0, scale: 0.85 }}
                                                className="hidden items-center gap-1.5 rounded-full border border-violet/40 bg-violet/10 px-3 py-1.5 text-[11px] text-violet sm:flex"
                                            >
                                                <Layers className="h-3 w-3" />
                                                <span className="font-medium">
                                                    {activeSections.length} section{activeSections.length !== 1 ? "s" : ""} · {tone}
                                                </span>
                                            </motion.span>
                                        ) : (
                                            <motion.span
                                                key="industry-pill"
                                                initial={{ opacity: 0 }}
                                                animate={{ opacity: 1 }}
                                                exit={{ opacity: 0 }}
                                                className="hidden rounded-full border border-hairline bg-surface-2/60 px-3 py-1.5 text-xs text-muted-foreground sm:inline-flex"
                                            >
                                                <span className="font-mono text-[10px] uppercase tracking-widest">Industry · Tech</span>
                                            </motion.span>
                                        )}
                                    </AnimatePresence>
                                </div>

                                <div className="flex items-center gap-2">
                                    <input
                                        ref={fileRef}
                                        type="file"
                                        multiple
                                        className="hidden"
                                        onChange={(e) => attach(e.target.files)}
                                    />
                                    <button
                                        onClick={() => fileRef.current?.click()}
                                        aria-label="Attach files"
                                        className="flex h-10 w-10 items-center justify-center rounded-full border border-magenta/40 bg-magenta/10 text-magenta transition hover:bg-magenta/20"
                                    >
                                        <Paperclip className="h-4 w-4" />
                                    </button>
                                    <motion.button
                                        whileTap={{ scale: 0.94 }}
                                        onClick={generate}
                                        disabled={phase === "thinking"}
                                        className="group relative flex items-center gap-2 overflow-hidden rounded-full bg-gradient-to-r from-violet to-magenta px-5 py-2.5 text-sm font-semibold text-white shadow-[var(--shadow-glow-violet)] transition hover:shadow-[var(--shadow-glow-magenta)] disabled:opacity-60"
                                    >
                                        {phase === "thinking" ? (
                                            <>
                                                <Wand2 className="h-4 w-4 animate-pulse" /> Generating…
                                            </>
                                        ) : (
                                            <>
                                                <Send className="h-4 w-4" /> Generate
                                            </>
                                        )}
                                    </motion.button>
                                </div>
                            </div>
                        </div>
                        {isDragging && (
                            <div className="pointer-events-none absolute inset-0 flex items-center justify-center rounded-[18px] bg-violet/10 text-sm font-medium text-violet">
                                Drop files to attach
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}

/* ============ FEATURE CARD ============ */

function FeatureCard({ feature, accents, index }) {
    const ref = useRef(null);
    const [glow, setGlow] = useState({ x: 50, y: 50, active: false });

    function handleMove(e) {
        const rect = ref.current?.getBoundingClientRect();
        if (!rect) return;
        setGlow({
            x: ((e.clientX - rect.left) / rect.width) * 100,
            y: ((e.clientY - rect.top) / rect.height) * 100,
            active: true,
        });
    }

    return (
        <motion.div
            ref={ref}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 + index * 0.08 }}
            whileHover={{ y: -4 }}
            onMouseMove={handleMove}
            onMouseLeave={() => setGlow((g) => ({ ...g, active: false }))}
            className={`glass group relative cursor-pointer overflow-hidden rounded-2xl p-4 ring-1 ${accents.ring}`}
        >
            <span
                className="pointer-events-none absolute inset-0 z-[1] rounded-2xl transition-opacity duration-300"
                style={{
                    opacity: glow.active ? 0.35 : 0,
                    background: `radial-gradient(140px circle at ${glow.x}% ${glow.y}%, ${accents.color}, transparent 70%)`,
                    mixBlendMode: "screen",
                }}
            />
            <div className="relative z-[2] flex items-center gap-3">
                <span
                    className={`flex h-9 w-9 items-center justify-center rounded-xl bg-surface-2 ring-1 ${accents.ring} ${accents.text}`}
                >
                    <Sparkles className="h-4 w-4" />
                </span>
                <div>
                    <p className="text-sm font-semibold text-foreground">{feature.title}</p>
                    <p className="text-xs text-muted-foreground">{feature.caption}</p>
                </div>
            </div>
        </motion.div>
    );
}

/* ============ THINKING STAGE ============ */

function ThinkingStage({
    files,
    stage,
    stageLabel,
    ticker,
    elapsed,
}) {
    const mm = String(Math.floor(elapsed / 60)).padStart(2, "0");
    const ss = String(elapsed % 60).padStart(2, "0");
    return (
        <div className="relative flex flex-col items-center">
            {/* Brain core with orbiting effects */}
            <div className="relative my-6 flex h-64 w-64 items-center justify-center">
                {/* glow halo */}
                <div className="absolute inset-0 rounded-full bg-gradient-to-br from-violet/30 via-cyan/20 to-magenta/30 blur-3xl" />
                {/* radial pulses */}
                <span className="radial-pulse absolute h-24 w-24 rounded-full border border-violet/40" />
                <span className="radial-pulse absolute h-24 w-24 rounded-full border border-cyan/40" style={{ animationDelay: "0.8s" }} />
                <span className="radial-pulse absolute h-24 w-24 rounded-full border border-magenta/40" style={{ animationDelay: "1.6s" }} />

                {/* orbits */}
                <div className="absolute inset-6 animate-spin rounded-full border border-dashed border-violet/40 [animation-duration:14s]" />
                <div className="absolute inset-12 animate-spin rounded-full border border-dashed border-cyan/40 [animation-direction:reverse] [animation-duration:10s]" />

                {/* particles */}
                {[...Array(8)].map((_, i) => {
                    const angle = (i / 8) * Math.PI * 2;
                    const r = 110;
                    return (
                        <motion.span
                            key={i}
                            initial={{ x: Math.cos(angle) * r, y: Math.sin(angle) * r, opacity: 0 }}
                            animate={{
                                x: [Math.cos(angle) * r, 0],
                                y: [Math.sin(angle) * r, 0],
                                opacity: [0, 1, 0],
                                scale: [1, 0.4],
                            }}
                            transition={{ duration: 1.6, delay: i * 0.2, repeat: Infinity, ease: "easeIn" }}
                            className="absolute h-1.5 w-1.5 rounded-full"
                            style={{
                                background: ["var(--violet)", "var(--cyan)", "var(--magenta)"][i % 3],
                                boxShadow: `0 0 12px ${["var(--violet)", "var(--cyan)", "var(--magenta)"][i % 3]}`,
                            }}
                        />
                    );
                })}

                {/* Files orbiting toward core */}
                {files.slice(0, 5).map((f, i) => {
                    const angle = (i / Math.max(files.length, 1)) * Math.PI * 2;
                    const radius = 130;
                    const x = Math.cos(angle) * radius;
                    const y = Math.sin(angle) * radius;
                    return (
                        <motion.div
                            key={f.id}
                            initial={{ x, y, opacity: 0, scale: 0.6 }}
                            animate={{
                                x: [x, x * 0.4, 0],
                                y: [y, y * 0.4, 0],
                                opacity: [0, 1, 0],
                                scale: [0.6, 1, 0.4],
                            }}
                            transition={{ duration: 2.4, repeat: Infinity, delay: i * 0.3, ease: "easeInOut" }}
                            className="absolute flex items-center gap-1.5 rounded-md border border-cyan/40 bg-surface-2/80 px-2 py-1 text-[10px] text-cyan shadow-[var(--shadow-glow-cyan)]"
                        >
                            <FileText className="h-3 w-3" />
                            <span className="max-w-[80px] truncate">{f.name}</span>
                        </motion.div>
                    );
                })}

                {/* Core */}
                <div className="pulse-ring relative z-10 flex h-24 w-24 items-center justify-center rounded-full bg-gradient-to-br from-violet via-magenta to-cyan shadow-[var(--shadow-glow-violet)]">
                    <Sparkles className="h-8 w-8 text-white" />
                </div>
            </div>

            {/* Indeterminate shimmer bar — no fake % */}
            <div className="w-full max-w-md">
                <div className="relative h-1.5 w-full overflow-hidden rounded-full bg-surface-2">
                    <div className="shimmer absolute inset-0 h-full" />
                </div>

                {/* Stage label + elapsed */}
                <div className="mt-3 flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                        <span className="flex gap-1">
                            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-cyan [animation-delay:0ms]" />
                            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-violet [animation-delay:150ms]" />
                            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-magenta [animation-delay:300ms]" />
                        </span>
                        <AnimatePresence mode="wait">
                            <motion.span
                                key={stage}
                                initial={{ opacity: 0, y: 6 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -6 }}
                                transition={{ duration: 0.3 }}
                                className="font-mono text-[10px] uppercase tracking-widest text-foreground/80"
                            >
                                {stageLabel}
                            </motion.span>
                        </AnimatePresence>
                    </div>
                    <span className="font-mono tabular-nums text-muted-foreground">{mm}:{ss}</span>
                </div>

                {/* Telemetry ticker — rotates real signals from backend */}
                <div className="mt-2 h-4 overflow-hidden text-center">
                    <AnimatePresence mode="wait">
                        <motion.div
                            key={ticker}
                            initial={{ opacity: 0, y: 8 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -8 }}
                            transition={{ duration: 0.35 }}
                            className="text-[11px] text-muted-foreground"
                        >
                            {ticker}
                        </motion.div>
                    </AnimatePresence>
                </div>
            </div>
        </div>
    );
}

/* ============ LENGTH SLIDER ============ */

function LengthSlider({ value, onChange }) {
    const active = LENGTH_OPTIONS[value];
    const pct = (value / (LENGTH_OPTIONS.length - 1)) * 100;
    return (
        <div
            className="hidden h-9 items-center gap-2 rounded-full border border-hairline bg-surface-2/60 px-3 sm:inline-flex"
            title={active.hint}
        >
            <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                Length
            </span>
            <input
                type="range"
                min={0}
                max={LENGTH_OPTIONS.length - 1}
                step={1}
                value={value}
                onChange={(e) => onChange(Number(e.target.value))}
                aria-label="Proposal length"
                className="length-slider w-20 cursor-pointer focus:outline-none"
                style={{ "--pct": `${pct}%` }}
            />
            <span className="min-w-[58px] text-[11px] font-medium text-foreground">{active.label}</span>
        </div>
    );
}

/* ============ RESULT CARD ============ */

function ResultCard({ onOpen, title, tone }) {
    return (
        <div className="space-y-4 pb-8">
            <div className="flex items-center gap-3">
                <span className="flex h-7 w-7 items-center justify-center rounded-md bg-violet/20 ring-1 ring-violet/40">
                    <Sparkles className="h-3.5 w-3.5 text-violet" />
                </span>
                <span className="font-mono text-[11px] uppercase tracking-widest text-violet">
                    Draftly · Draft ready
                </span>
                <span className="h-px flex-1 bg-gradient-to-r from-violet/40 to-transparent" />
            </div>

            <motion.button
                onClick={onOpen}
                whileHover={{ y: -4 }}
                whileTap={{ scale: 0.99 }}
                initial={{ opacity: 0, y: 14 }}
                animate={{ opacity: 1, y: 0 }}
                className="glass-strong group relative w-full overflow-hidden rounded-2xl p-6 text-left shadow-panel transition hover:border-violet/40"
            >
                {/* shimmer band */}
                <span className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-violet to-transparent opacity-60" />
                <span className="pointer-events-none absolute -bottom-20 -right-20 h-48 w-48 rounded-full bg-violet/30 opacity-50 blur-3xl transition group-hover:opacity-80" />

                <div className="flex items-start justify-between gap-4">
                    <div className="min-w-0 flex-1">
                        <p className="font-mono text-[10px] uppercase tracking-widest text-cyan">Proposal · {tone}</p>
                        <h2 className="mt-1.5 truncate font-display text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
                            {title}
                        </h2>
                        <p className="mt-2 max-w-xl text-sm text-muted-foreground">
                            {sampleProposalSections.length} sections drafted — Executive Summary, Scope, Timeline, Team, Investment, Next Steps. Click to open in editor.
                        </p>
                    </div>
                    <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-violet to-magenta text-white shadow-[var(--shadow-glow-violet)] transition group-hover:scale-110">
                        <ArrowRight className="h-5 w-5" />
                    </span>
                </div>

                {/* mini section preview chips */}
                <div className="mt-5 flex flex-wrap gap-1.5">
                    {sampleProposalSections.map((s, i) => (
                        <motion.span
                            key={s.id}
                            initial={{ opacity: 0, y: 6 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.2 + i * 0.06 }}
                            className="rounded-md border border-hairline bg-surface-2/60 px-2 py-1 text-[10px] text-foreground/80"
                        >
                            {String(i + 1).padStart(2, "0")} · {s.title}
                        </motion.span>
                    ))}
                </div>

                <div className="mt-5 flex items-center justify-between border-t border-hairline pt-4 text-xs">
                    <span className="text-muted-foreground">Open in editor to refine each section</span>
                    <span className="font-mono uppercase tracking-widest text-violet group-hover:text-magenta">
                        Open editor →
                    </span>
                </div>
            </motion.button>
        </div>
    );
}
