# Generated by Django 5.0.6 on 2026-06-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stripeevent',
            new_name='billing_str_receive_7f9bbf_idx',
            old_name='billing_str_receive_idx',
        ),
    ]
