# Generated by Django 5.0.6 on 2026-05-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pricing_model_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
