# Generated by Django 5.0.6 on 2026-06-10 17:02

from django.db import migrations, models


def backfill_null_avatar_urls(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(avatar_url__isnull=True).update(avatar_url="")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_terms_accepted_at"),
    ]

    operations = [
        migrations.RunPython(backfill_null_avatar_urls, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
